name: cartelera_digital_mobile
description: Aplicación móvil para la Cartelera Digital
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  shared_preferences: ^2.2.2
  http: ^1.1.0
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  cached_network_image: ^3.3.1
  video_player: ^2.7.2
  flutter_cache_manager: ^3.3.1
  path: ^1.8.3
  intl: ^0.19.0
  socket_io_client: ^2.0.3+1
  file_picker: ^6.1.1
  web_socket_channel: ^2.4.0
  flutter_dotenv: ^5.1.0
  logger: ^2.0.2
  animate_do: ^3.1.2
  flutter_animate: ^4.5.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Logo_SIMCUV.png
    - .env
    - assets/images/
