name: cartelera_digital_mobile
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  http: ^1.1.0
  google_fonts: ^6.1.0
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  socket_io_client: ^2.0.3



  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^4.0.0


flutter:

  
  uses-material-design: true

  #

  assets:
    - assets/Logo_SIMCUV.png
