name: cartelera_digital
description: "A new Flutter project"

# Agregar esta sección
environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  google_fonts: ^6.1.0
  animate_do: ^3.0.2
  animated_text_kit: ^4.2.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  syncfusion_flutter_charts: ^27.2.3
  shared_preferences: ^2.2.2
  flutter_colorpicker: ^1.0.3
  file_picker: ^8.1.4
  video_player: ^2.8.1
  path_provider: ^2.1.2
  path: ^1.8.3
  flutter_secure_storage: ^9.0.0
  riverpod_annotation: ^2.3.3
  msix: ^3.16.7
  mysql1: ^0.20.0
  image: ^4.1.3
  lottie: ^3.1.3
  logger: ^2.0.2+1
  http: ^1.1.0
  shelf: ^1.4.1
  shelf_router: ^1.1.3
  flutter_dotenv: ^5.1.0
  socket_io_client: ^2.0.3+1
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/SIMCUV_icon.ico
    - assets/images/Logo_SIMCUV.png
    - assets/animations/Analysis_Animation.json
    - assets/animations/Dashboard_Animation.json
    - assets/animations/Loading_Animation.json
  

msix_config:
  display_name: Cartelera Digital
  publisher_display_name: SIMCU
  identity_name: com.simcu.cartelera_digital
  logo_path: assets/images/SIMCUV_icon.ico
  capabilities: internetClient